### PR TITLE
Import user places from text

### PR DESCRIPTION
**Pull request by forman**
Added function to insert user places from text. (#88)

Features

- Import places from geometry text using formats CSV/Text, GeoJSON, and WKT
- Text editor
- Open text from file
- Drag & drop a text file into editor
- Drag & drop multiple files onto map (check: allow only single files and open editor dialog so users can add options?)
- CSV/Text format
  - Options: 
     - Name of x/y columns or geometry column
     - Name of label column
     - CSV parser options, e.g., separator, quote, escape, etc., tokens for NaN, true, false.
- GeoJSON format
  - Supported types are all Geometries, Feature, and FeatureCollection
  - Syntax hi-lighting 
  - Options: 
    - Name of property used as label 
- WKT format
  - Options: 
     - Name of x/y columns or geometry column
     - CSV parser options, e.g., separator, quote, escape, etc., tokens for NaN, true, false.
  
image

image

image

TODO:

- [x] i18n it, currently EN only.
- [ ] Import many features into own user place group.
     - [ ] Switch visibility of user place group, currently always shown;
     - [ ] Delete user place group entirely, currently only single user places can be deleted.
- [ ] Opt: allow entering label as combination of CSV column names or GeoJSON property names. 
       Default is column/property named "label".
- [ ] Opt: allow entering character encoding, currently assuming UTF-8.
- [ ] Opt: allow entering data CRS, currently assuming EPSG:4326.
- [ ] Opt: allow entering style/color column, currently fixed to name "color". Default color is "red".
- [ ] Opt: allow importing a large number of points as point clusters.
- [ ] Opt: validate also CSV and WKT in dialog, currently we only do that for GeoJSON.
- [ ] Opt: add syntax hi-lighting also for CSV and WKT

### CODE REVIEW

**Comment by AliceBalfanz** [comment]
Using light mode of viewer makes the OK button look, like it is not active. It is active though and works well. Can you make sure that the OK button appears "available" in light mode as well?
image


When loading in a geojson, which is is not valid, the following screen appears: 
image
when clicking to remove popup "No data found here" the following view appears: 
image

Both views are misleading, and break the visualisation of the viewer. Maybe this can be handeled differently? I can provide the geojson I used for testing.

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
See comment and screenshots.

**Comment by forman** [comment]
> Using light mode of viewer makes the OK button look, like it is not active. It is active though and works well. Can you make sure that the OK button appears "available" in light mode as well?

Weird. I'll check.

> When loading in a geojson, which is is not valid, the following screen appears
> Both views are misleading, and break the visualisation of the viewer. Maybe this can be handeled differently? 

Yes, see features list above:

* Drag & drop multiple files onto map (check: allow only single files and open editor dialog so users can add options?)

So, that's how I'll do it: allow only single file and open editor dialog so users can check and adjust options.

**Comment by forman** [comment]
> Using light mode of viewer makes the OK button look, like it is not active. It is active though and works well. Can you make sure that the OK button appears "available" in light mode as well? image
> 
> When loading in a geojson, which is is not valid, the following screen appears: image when clicking to remove popup "No data found here" the following view appears: image
> 
> Both views are misleading, and break the visualisation of the viewer. Maybe this can be handeled differently? I can provide the geojson I used for testing.

This does not occur in an un-branded version:

image

**Review by AliceBalfanz — APPROVED** [review]
Apart from issues with firefox it works really well with Chrome!

**Pull request merged**
