### PR TITLE
Forman fix colors

### PR DESCRIPTION
**Pull request by forman**
@AliceBalfanz and @dzelge There is no related issue as all of the issues fixed are related to new, buggy features - they are regressions. Please verify that this PR does the following:

- [x] Using same colors for all TSes created from the same geo point.
- [ ] When time series charts are set to display points only (don't show lines), the TS points will now stay in the geo point's color.
- [x] Selected places are now highlighted in the map

### CODE REVIEW

**Comment by AliceBalfanz** [comment]
There is an issue with changing from the line view to point view of the data points in the time series. When one changes the view after having already calculated time series for several variables and points, only the most recent time series stays, the others disappear. The same happens, when point view is selected from the beginning and then time series are calculated. Only the most recent one stays visible. Interestingly, then switching to a different data cube without deleting the time series from the prior data cube, all former graphs are displayed in the expected manner (i.e. they become visible again). 

grafik

grafik

grafik

Another issue that appeared: The preconfigured places corresponding to a data cube are displayed twice in the places list. 
grafik

**Comment by forman** [comment]
I'll check...

**Comment by forman** [comment]
> * Ich kann keinen Kreis malen, ohne die shifttaste zu drücken

There is no Kreis in this PR.

> * Mein PR ist nicht drin

Your PR has only be accepted this morning and is on master.

**Comment by dzelge** [comment]
grafik

**Comment by forman** [comment]
You are on the wrong branch. Your are on PR #87

**Comment by forman** [comment]
> When a point is newly created it is automatically selected (which makes sense) but not highlighted.

Yes, I couldn't figure out why this happens!

**Pull request merged**
