### PR TITLE
xcube JupyterLab integration

### PR DESCRIPTION
**Pull request by forman**
* Can now run xcube Viewer in "compact" mode. This is
  primarily used for the JupyterLab integration.
  To enable compact mode, pass query parameter `compact=1`.

To test, [xcube JupyterLab extension](https://github.com/dcs4cop/xcube-jl-ext) must be enabled in JupyterLab.
Please install development version first as described in its [README](https://github.com/dcs4cop/xcube-jl-ext/blob/main/README.md).
**Important:** Use xcube PR https://github.com/dcs4cop/xcube/pull/775.

### CODE REVIEW

**Comment by AliceBalfanz** [comment]
It is not possible to zoom into the end of a time series anymore: 
Related closed issue: https://github.com/dcs4cop/xcube-viewer/issues/163

**Comment by forman** [comment]
> It is not possible to zoom into the end of a time series anymore if you drag the field further than the end of the time series- it does not crash but nothing happens. Related closed issue: #163

It is this specific to this PR?

**Comment by AliceBalfanz** [comment]
Not sure - I will create an issue and this should not be blocking merging the PR.

**Comment by forman** [comment]
> Not sure - I will create an issue and this should not be blocking merging the PR.

You should create an issue only if you observe the issue in a released version.

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
I have tested the python code extention, which has a problem with providing the correct ID for opening the dataset. 

```
from xcube.core.store import new_data_store

store = new_data_store(
    "s3",
    root="datasets",  # can also use "pyramids" here
    storage_options={
        "anon": True,
        "client_kwargs": {
            "endpoint_url": "http://localhost:8080/s3"
        }
    }
)
# store.list_data_ids()
dataset = store.open_data("deep-esdl~black-sea-1x1024x1024.levels.zarr")
```

output of 
`store.list_data_ids()`

```
['black-sea-time-optimized.zarr',
 'deep-esdl~black-sea-1x1024x1024.zarr',
 'deep-esdl~esdc-8d-0.25deg-1x720x1440-3.0.1.zarr',
 'esdc-time-optimized.zarr']
```

**Comment by AliceBalfanz** [comment]
`compact` parameter breaks custom viewer configuration:
image
using `compact=1`
image
using `compact=0`
image

**Comment by forman** [comment]
> `compact` parameter breaks custom viewer configuration:

I'll have a look. However, this should not block us right now, because this mode is only used programmatically for the xcube JupyterLab integration where we (currently) have no custom branding.

**Comment by forman** [comment]
> `compact` parameter breaks custom viewer configuration

Please use a question mark to separate query arguments from the URL: http://localhost:3000?compact=1

**Review by AliceBalfanz — APPROVED** [review]
Thank you for clarifications and fixing the python snippet :)

**Pull request merged**
