### PR TITLE
Adjustments of xcube viewer gha workflow

### PR DESCRIPTION
**Pull request by AliceBalfanz**
This PR removes code duplication and fixes some typos.

### CODE REVIEW

**Review by forman — COMMENTED** [review]
Fine by me!

However, the filename for `xcube-viewer_workflow.yaml` looks inconsistent. Can we please consistently use "_" and "-"? Thus either
- `xcube-viewer-workflow.yaml` 
- `xcube_viewer_workflow.yaml`

**Review by dzelge — APPROVED** [review]

**Comment by AliceBalfanz** [comment]
> Fine by me!
> 
> However, the filename for `xcube-viewer_workflow.yaml` looks inconsistent. Can we please consistently use "_" and "-"? Thus either
> 
>     * `xcube-viewer-workflow.yaml`
> 
>     * `xcube_viewer_workflow.yaml`

Depends, what we mean by inconsistent. If we always take the repo name and then _workflow.yaml for the gha, then the file name xcube-viewer_workflow.yaml is consistent. 

But happy to change if everybody wants a change.

**Review by TonioF — APPROVED** [review]

**Comment by TonioF** [comment]
> > Fine by me!
> > However, the filename for `xcube-viewer_workflow.yaml` looks inconsistent. Can we please consistently use "_" and "-"? Thus either
> > ```
> > * `xcube-viewer-workflow.yaml`
> > 
> > * `xcube_viewer_workflow.yaml`
> > ```
> 
> Depends, what we mean by inconsistent. If we always take the repo name and then _workflow.yaml for the gha, then the file name xcube-viewer_workflow.yaml is consistent.
> 
> But happy to change if everybody wants a change.

I prefer the option `xcube-viewer-workflow.yaml`. However, I quickly checked and it seems we have not been using this consistently across projects, so a decision on this is welcome anyway.

**Review by forman — CHANGES_REQUESTED** [review]
> I prefer the option xcube-viewer-workflow.yaml. However, I quickly checked and it seems we have not been using this consistently across projects, so a decision on this is welcome anyway.

So this is inconsistent and therefore please change the name to `xcube-viewer-workflow.yam`. And from now on, we'll try to be consistent.

**Comment by AliceBalfanz** [comment]
Alright, renamed the file and merging :)

**Pull request merged**
