### PR TITLE
Turn off image smoothing, part 2

### LINKED ISSUE #181: Turn off image smoothing, part 2
It is now possible to tell OpenLayers to now turn off do image smoothing: https://openlayers.org/en/latest/examples/disable-image-smoothing.html

We have achieved this by a hack, see #86 and https://github.com/openlayers/openlayers/issues/10273. Instead, use new OpenLayers option now.

### PR DESCRIPTION
**Pull request by forman**
Closes #181

> Not accepting yet: first problem with data being displayed somewhere else needs to to be fixed. see screenshot - data should be covering the data of back sea, but appears in germany instead.

Just fixed that!

### CODE REVIEW

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
Not accepting yet: first problem with data being displayed somewhere else needs to to be fixed. see screenshot - data should be covering the data of back sea, but appears in germany instead. 
image

**Comment by AliceBalfanz** [comment]
Something is off - I cannot test it with xcube's current master version: 
I am using the edc Identifier with: 

```
  - Identifier: edc
    StoreId: s3
    StoreParams:
      # root: eurodatacube-scratch/2021-09-09/SERVICE-DEV
      root: eurodatacube-scratch/2021-09-13/SERVICE-DEV
      max_depth: 4
      fs_params:
        anon: true
        # client_kwargs:
        #  endpoint_url: https://s3.eu-central-1.amazonaws.com
    Datasets:
      - Identifier: "*.zarr"
        Style: "default"
        # ChunkCacheSize: 1G
```
and the server logs errors as soon as the viewer is requesting data:

```
[I 210913 13:37:33 service:239] configuration file '/home/alicja/Desktop/projects/xcube/examples/serve/demo/config-with-stores.yml' successfully loaded
[I 210913 13:37:33 service:168] service running, listening on localhost:8080, try http://localhost:8080/datasets
[I 210913 13:37:33 service:169] press CTRL+C to stop service
[I 210913 13:37:39 perf:79] get granted scopes: took 0.04ms
[I 210913 13:37:39 context:283] scanning store 'edc'
tornado.application - ERROR - Uncaught exception GET /datasets?details=1&tiles=ol4 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/datasets?details=1&tiles=ol4', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/alicja/miniconda3/envs/xcube/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/handlers.py", line 133, in get
    response = get_datasets(self.service_context,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/controllers/catalogue.py", line 96, in get_datasets
    get_dataset(ctx, ds_id, client,
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/controllers/catalogue.py", line 158, in get_dataset
    tile_grid = ctx.get_tile_grid(ds_id)
  File "/home/alicja/Desktop/projects/xcube/xcube/webapi/context.py", line 387, in get_tile_grid
    return ml_dataset.tile_grid
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset.py", line 153, in tile_grid
    self._tile_grid = self._get_tile_grid_lazily()
  File "/home/alicja/Desktop/projects/xcube/xcube/core/mldataset.py", line 211, in _get_tile_grid_lazily
    return self.grid_mapping.tile_grid
  File "/home/alicja/Desktop/projects/xcube/xcube/core/gridmapping/base.py", line 776, in tile_grid
    assert_true(math.isclose(self.x_res, self.y_res),
  File "/home/alicja/Desktop/projects/xcube/xcube/util/assertions.py", line 106, in assert_true
    raise exception_type(message)
ValueError: spatial resolutions must be same in both directions
```

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
See my comment and error traceback.

**Comment by forman** [comment]
> See my comment and error traceback.

Right, I just observed the same issue. xcube PR follows.

**Comment by forman** [comment]
@AliceBalfanz it should now work with https://github.com/dcs4cop/xcube/pull/526

**Review by AliceBalfanz — APPROVED** [review]
Thanks for the changes :)

**Pull request merged**
