### PR TITLE
Display 2D datasets

### PR DESCRIPTION
**Pull request by forman**
This PR allows displaying also 2D datasets such as opened from GeoTIFF / COG files.

**IMPORTANT:** Requires https://github.com/dcs4cop/xcube/pull/689

### CODE REVIEW

**Comment by TejasMorbagal** [comment]
The calendar and navigation buttons should be disabled for 2D datasets

**Review by TejasMorbagal — CHANGES_REQUESTED** [review]
The calendar and navigation buttons should be disabled for 2D datasets

**Comment by forman** [comment]
> The calendar and navigation buttons should be disabled for 2D datasets

I agree.

**Review by TejasMorbagal — APPROVED** [review]
Works as expected

**Pull request merged**
