### PR TITLE
Forman 86 avoid image smoothing

### LINKED ISSUE #86: Turn off smoothing of tile pixels
Users don't want any pixel interpolation applied to their tile layers. They want crisp (Earth observation) image pixels to be shown.
        
I've already tried various solutions, but none worked out so far, see also

* https://stackoverflow.com/questions/54083424/preventing-smoothing-of-tileimage-layer
* https://stackoverflow.com/questions/35875270/turn-off-image-smoothing-in-openlayers-3
* https://openlayers.org/en/latest/examples/layer-spy.html

### PR DESCRIPTION
**Pull request by forman**
Closes #86 

... for time being, as the solution is an ugly hack. I had to [exchange](https://github.com/dcs4cop/xcube-viewer/blob/76e4d3579f256da0ac35c11c1994d00408502fdb/src/util/hacks.ts) the global HTMLCanvasElement.getContext() implementation to make it work. Disabling image smoothing now unfortunately applies to all layers.

Find the new setting in the settings dialog.

### CODE REVIEW

**Comment by forman** [comment]
> Du hast wahrscheinlich auch schon diese Warnungen gesehen, wenn man die Seite lädt (das passier in OCDB auch):

Ja, kann ich erstmal nichts machen, das kommt von `recharts`, nicht aus unserem Code.

**Comment by forman** [comment]
> The legend is not there anymore when selecting the time series visualisation for a point, is it possible to fix this?

image

Hopefully, I had crashes in OpenLayer 4.x, maybe it now works for 6.1.1.

**Comment by forman** [comment]
Fixed. In addition, the color bar legend now uses 5 tick marks instead of the two.

**Comment by AliceBalfanz** [comment]
Same issue as dzelge described, happens for the custom SNAP colormaps. Empty color legend:
 
grafik

**Pull request merged**
